version: "3.9"

services:
  web:
    build: .
    container_name: rams-web
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    # no ports directly; nginx will expose 80/443
    depends_on: []

  nginx:
    image: nginx:1.27
    container_name: rams-nginx
    restart: always
    ports:
      - "80:80"
      # later: "443:443" when you add HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
